### ISSUE TITLE
Icons for file types aren't showing up

### ISSUE THREAD

**Issue by ves-krd** [domkl14/Monokai-Minified-Sublime-Theme#1]
Sublime Version 3.1.1
Build 3176

Installed by putting in a folder in Packages called "Monokai-Minified-Sublime-Theme"

**Comment by domkl14** [comment]
I don't believe my theme provides file icons. Try installing the package [A File Icon](https://github.com/ihodev/a-file-icon).

**Comment by ves-krd** [comment]
Thanks, I didn't know where the icons were coming from, assumed they were theme specific.
